cli: make action a required argument
Otherwise you get this error:

    $ python -m chipflow_lib.cli
      File ".../chipflow-lib/chipflow_lib/cli.py", line 51, in run
        getattr(self, 'run_' + args.action)(args)
    TypeError: can only concatenate str (not "NoneType") to str